Add first tests

diff --git a/loin b/loin
--- a/loin
+++ b/loin
@@ -64,9 +64,14 @@ function openBookmarks {
 # set default mode
 MODE="open"
 
+BADARGERROR='Error: loin takes no arguments, run in Tag-Mode by specifying the flag "--tag"'
+
 # parse tag mode command line flag
 if [ "$1" = "--tag" ]; then
 	MODE="tag"
+elif [ -n $1 ]; then
+	echo "$BADARGERROR"
+	exit 1
 fi
 
 # execute
